services:
  db:
    image: docker.m.daocloud.io/postgres:18-alpine
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
    driver: local